version: "2.4"

services:
  localnet:
    build: containers/localnet
    ports:
      - "7950:7950"
    environment:
      - MX_LT_ELASTIC_ENABLED
      - MX_LT_NUM_SHARDS
      - MX_LT_CUSTOM_EGLD_ADDRESS

  mysql:
    image: "mysql:latest"

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api

  api:
    build: containers/api
    ports:
      - "3001:3001"

  elastic:
    image: elasticsearch:7.17.8
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      discovery.type: single-node

  redis:
    image: "redis:alpine"

    command: redis-server

    environment:
      - REDIS_REPLICATION_MODE=master

  rabbitmq:
    image: rabbitmq:3.11.8
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  xexplorer:
    build: containers/xexplorer
    ports:
      - "3002:3002"
