[StakingSystemSCConfig]
GenesisNodePrice = "2500000000000000000000"
MinStakeValue = "100000000000000000000"
MinUnstakeTokensValue = "10000000000000000000"
UnBondPeriod = 250
UnBondPeriodInEpochs = 1
MinStepValue = "100000000000000000000"
NumRoundsWithoutBleed = 100
MaximumPercentageToBleed = 0.5
BleedPercentagePerRound = 1e-5
MaxNumberOfNodesForStake = 36
UnJailValue = "2500000000000000000"
ActivateBLSPubKeyMessageVerification = true

[ESDTSystemSCConfig]
BaseIssuingCost = "50000000000000000" #0.05 eGLD
OwnerAddress = "erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c"
EnabledEpoch = 0

[GovernanceSystemSCConfig]
FirstWhitelistedAddress = "erd1vxy22x0fj4zv6hktmydg8vpfh6euv02cz4yg0aaws6rrad5a5awqgqky80" #should use a multisign contract instead of a wallet address
EnabledEpoch = 0

[GovernanceSystemSCConfig.V1]
NumNodes = 500
ProposalCost = "5000000000000000000"
MinQuorum = 400
MinPassThreshold = 300
MinVetoThreshold = 50

[GovernanceSystemSCConfig.Active]
ProposalCost = "5000000000000000000"
MinQuorum = "500000000000"
MinPassThreshold = "251000000000"
MinVetoThreshold = "249000000000"

[DelegationManagerSystemSCConfig]
MinCreationDeposit = "1250000000000000000000"
MinStakeAmount = "10000000000000000000"
ConfigChangeAddress = "erd1vxy22x0fj4zv6hktmydg8vpfh6euv02cz4yg0aaws6rrad5a5awqgqky80"
EnabledEpoch = 1

[DelegationSystemSCConfig]
MinServiceFee = 0
MaxServiceFee = 10000
EnabledEpoch = 1
