[networking]
port_proxy = 7950

[software]
resolution = "local_prebuilt_cmd_folders"

[software.local_prebuilt_cmd_folders]
# Has to contain "node" binary, "config" folder, wasmer libraries
mx_chain_go_node = "/home/ubuntu/mx-chain-go/cmd/node"
# Has to contain "seednode" binary, "config" folder, wasmer libraries
mx_chain_go_seednode = "/home/ubuntu/mx-chain-go/cmd/seednode"
# Has to contain "proxy" binary, "config" folder, wasmer libraries
mx_chain_proxy_go = "/home/ubuntu/mx-chain-proxy-go/cmd/proxy"
