[config]
    [config.input]
        url = "http://127.0.0.1:9200"
        username = ""
        password = ""

    [config.output]
        url = "http://127.0.0.1:9200"
        username = ""
        password = ""

    [config.indices]
        indices-no-timestamp = ["accounts","rating", "validators", "epochinfo", "tags", "delegators"]
        [config.indices.with-timestamp]
            enabled = true
            num-parallel-writes = 20
            blockchain-start-time = 1596117600 # mainnet start time ( for testnet will be a different start time)
            indices-with-timestamp = ["accountsesdt", "tokens", "blocks", "receipts", "transactions","miniblocks", "rounds",  "accountshistory", "scresults", "accountsesdthistory", "scdeploys", "logs", "operations"]
