get-dependencies: |
	cd dbMerger && go get -v -t -d ./...
	cd elasticreindexer && go get -v -t -d ./...
	cd tokensRemover && go get -v -t -d ./...
	cd trieTools && go get -v -t -d ./...

test: |
	cd dbMerger && go test ./...
	cd elasticreindexer && go test ./...
	cd tokensRemover && go test ./...
	cd trieTools && go test ./...
