name: Build

on:
  pull_request:
    branches: [main]
    types: [opened, ready_for_review]
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    name: Build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/dbMerger/cmd/generalDBMerger && go build .
          cd ${GITHUB_WORKSPACE}/elasticreindexer/cmd/elasticreindexer && go build .
          cd ${GITHUB_WORKSPACE}/elasticreindexer/cmd/indices-creator && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/accountStorageExporter && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/balancesExporter && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/tokensExporter && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/trieChecker && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/trieStatsPrinter && go build .
          cd ${GITHUB_WORKSPACE}/trieTools/zeroBalanceSystemAccountChecker && go build .
